name       : umbrello
version    : 18.04.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.0/src/umbrello-18.04.0.tar.xz : b7f9f48bfdf6ce5d61738975a318c09ed4f0b3d41c6b8b4f57184902a4406ed1
license    : GPL-2.0
component  : programming.tools
optimize   : lto
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=1
build      : |
    %ninja_build
install    : |
    %ninja_install
