name       : umbrello
version    : 17.12.2
release    : 16
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.2/src/umbrello-17.12.2.tar.xz : 24ad73fd6db5d660b361e43c32349f9e2f3b8597bb1a638ba6547baf5d6ea0ea
license    : GPL-2.0
component  : programming.tools
optimize   : lto
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
