name       : umbrello
version    : 17.12.3
release    : 17
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.3/src/umbrello-17.12.3.tar.xz : 20c36aaf4c7e7ace87c56839d7c5a1fbadab5b244d92d2f17d1bab8475e47848
license    : GPL-2.0
component  : programming.tools
optimize   : lto
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
