name       : umbrello
version    : 17.04.0
release    : 5
source     :
    - https://download.kde.org/stable/applications/17.04.0/src/umbrello-17.04.0.tar.xz : d6fde01d10016efd12e9bcb547c3a375124a7f6cde7b2be6b5c40f4526ce6a36
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - clang-devel
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    # Unittests not currently working
    sed -i 's/BUILD_UNITTESTS 1/BUILD_UNITTESTS 0/' CMakeLists.txt
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
