name       : umbrello
version    : 16.12.1
release    : 4
source     :
    - http://download.kde.org/stable/applications/16.12.1/src/umbrello-16.12.1.tar.xz : 2ccd645ab52544885e3b373b0da543ae171d8b41a0bdeb93ae45170f8cd30bb9
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - clang-devel
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
