name       : umbrello
version    : 20.12.2
release    : 60
source     :
    - https://cdn.download.kde.org/stable/release-service/20.12.2/src/umbrello-20.12.2.tar.xz : 4e4fdc0cbff6d578d6e2510c186a27e402995d35265ac203e100e6950c61f17f
homepage   : https://kde.org/applications/development/org.kde.umbrello
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - grantlee-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kdev-php-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - ktexteditor-devel
    - threadweaver-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    #Remove docs
    rm -rf $installdir/usr/share/doc
    rm -rf $installdir/usr/share/umbrello5/apidoc
