name       : umbrello
version    : 23.04.2
release    : 81
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/umbrello-23.04.2.tar.xz : 2e643111347fb79f40321f82725f92c293cd3bc6bba75f3caf912b3fa0b7fb00
homepage   : https://kde.org/applications/development/org.kde.umbrello
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Quick)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - grantlee-devel
    - kcmutils-devel
    - kdelibs4support-devel
    - kdev-php-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - ktexteditor-devel
    - threadweaver-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=ON
build      : |
    %ninja_build
install    : |
    %ninja_install

    #Remove docs
    rm -rf $installdir/usr/share/doc
    rm -rf $installdir/usr/share/umbrello5/apidoc
