name       : umbrello
version    : 20.04.3
release    : 52
source     :
    - https://cdn.download.kde.org/stable/release-service/20.04.3/src/umbrello-20.04.3.tar.xz : c34a5f6ca945dd409921903abd2e0078b6a056a0d221d59674980ce424cf1e62
homepage   : https://kde.org/applications/development/org.kde.umbrello
license    :
    - GFDL-1.2-or-later
    - GPL-2.0-or-later
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - grantlee-devel
    - kcmutils-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - ki18n-devel
    - kio-devel
    - knewstuff-devel
    - knotifyconfig-devel
    - ktexteditor-devel
    - llvm-clang-devel
    - threadweaver-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=ON
build      : |
    %ninja_build
install    : |-
    %ninja_install

    #Remove docs
    rm -rf $installdir/usr/share/doc
    rm -rf $installdir/usr/share/umbrello5/apidoc
