name       : umbrello
version    : 18.04.2
release    : 21
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/umbrello-18.04.2.tar.xz : adace35eb1e8e1e4f8521fb57661d0d61888e3065322bf40e81b960077b3243e
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=1
build      : |
    %ninja_build
install    : |
    %ninja_install
