name       : umbrello
version    : 17.12.1
release    : 15
source     :
    - https://cdn.download.kde.org/stable/applications/17.12.1/src/umbrello-17.12.1.tar.xz : 29c84549c5b09edf749826e67e33ffc0c65a2ef1aaf14f4e861910f4be5c798e
license    : GPL-2.0
component  : programming.tools
optimize   : lto
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
