name       : umbrello
version    : 17.04.3
release    : 9
source     :
    - https://download.kde.org/stable/applications/17.04.3/src/umbrello-17.04.3.tar.xz : 7a890d1d9da267c2980c4165a9558ec2ea3c638641462c82afce6556244926ec
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    # Unittests not currently working
    sed -i 's/BUILD_UNITTESTS 1/BUILD_UNITTESTS 0/' CMakeLists.txt
    %patch -p1 < $pkgfiles/0001-Fix-Budgie-entry.patch
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
