name       : umbrello
version    : 18.04.1
release    : 20
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.1/src/umbrello-18.04.1.tar.xz : 1e6251c232dfea2fee825899a7eeed54efb59938b153a0f0d8b79e6a8bbf88ef
license    : GPL-2.0
component  : programming.tools
optimize   : lto
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdevelop-devel
    - kdevelop-pg-qt-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_KF5=1
build      : |
    %ninja_build
install    : |
    %ninja_install
