name       : umbrello
version    : 16.08.3
release    : 2
source     :
    - http://download.kde.org/stable/applications/16.08.3/src/umbrello-16.08.3.tar.xz : 4ddf96305a11d850530391c6ea3da3fcf31dec26bab6250a20387a7f4fe02c64
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Svg)
    - clang-devel
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
setup      : |
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
