name       : umbrello
version    : 17.04.2
release    : 8
source     :
    - https://download.kde.org/stable/applications/17.04.2/src/umbrello-17.04.2.tar.xz : 618a90643d2041b57a0d1efeef1fa22a73174052946ef1ccbb40258db68b1d4a
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    # Unittests not currently working
    sed -i 's/BUILD_UNITTESTS 1/BUILD_UNITTESTS 0/' CMakeLists.txt
    %patch -p1 < $pkgfiles/0001-Fix-Budgie-entry.patch
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
