name       : umbrello
version    : 17.08.3
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/17.08.3/src/umbrello-17.08.3.tar.xz : e0c8845e03c251c9e8b33f9d3e09d312c5e8f6b8200f84f5d3610970a74d24bc
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - extra-cmake-modules
    - karchive-devel
    - kcrash-devel
    - kdelibs4support-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
    - llvm-clang-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-Budgie-entry.patch
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
