name       : umbrello
version    : 17.04.1
release    : 6
source     :
    - https://download.kde.org/stable/applications/17.04.1/src/umbrello-17.04.1.tar.xz : 7bc0f0366035d0ade7f50c9cbb661e427f527e25a39ea453910400fbf26fb336
license    : GPL-2.0
component  : programming.tools
summary    : Umbrello UML Modeller is a UML diagramming tool for KDE
description: |
    Umbrello UML Modeller is a UML diagramming tool for KDE
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(libxslt)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5WebKit)
    - clang-devel
    - extra-cmake-modules
    - karchive-devel
    - kdoctools-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - ktexteditor-devel
    - kwindowsystem-devel
setup      : |
    # Unittests not currently working
    sed -i 's/BUILD_UNITTESTS 1/BUILD_UNITTESTS 0/' CMakeLists.txt
    %cmake -DBUILD_KF5=1 .
build      : |
    %make
install    : |
    %make_install
